title: Harry Chang # your name (or website title) here
logo: "https://github.com/HarryChangData/HarryChangData.GitHub.io/blob/master/images/DSC06687-min.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MBA Candidate / Data Analyst / Operations 
  Symphony violinist after sunset  <br><br>
  <a href="https://www.linkedin.com/in/harrychang007/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
